CITIES_DB = {
    "US": [
        "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio",
        "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus",
        "Charlotte", "Indianapolis", "San Francisco", "Seattle", "Denver", "Washington DC",
        "Nashville", "Oklahoma City", "El Paso", "Boston", "Portland", "Las Vegas", "Memphis",
        "Louisville", "Baltimore", "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Sacramento",
        "Mesa", "Kansas City", "Atlanta", "Omaha", "Colorado Springs", "Raleigh", "Long Beach",
        "Virginia Beach", "Miami", "Oakland", "Minneapolis", "Tulsa", "Tampa", "Arlington",
        "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu",
        "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Stockton", "St. Louis",
        "Pittsburgh", "Cincinnati", "Anchorage", "Henderson", "Greensboro", "Plano", "Newark",
        "Lincoln", "Orlando", "Jersey City", "Chandler", "St. Paul", "Laredo", "Scottsdale",
        "Madison", "Buffalo", "Gilbert", "Fremont", "North Las Vegas", "Winston-Salem",
        "Chesapeake", "Lubbock", "Glendale", "Reno", "Baton Rouge", "Richmond", "Boise",
        "Spokane", "Des Moines", "Tacoma", "San Bernardino", "Modesto", "Fontana",
        "Moreno Valley", "Santa Clarita", "Birmingham", "Rochester", "Syracuse", "Montgomery",
        "Boise City", "Pueblo", "Fargo", "Sioux Falls", "Cedar Rapids", "Davenport",
        "Wichita Falls", "Amarillo", "Lubbock", "Abilene", "Odessa", "Midland", "Tyler",
        "Waco", "College Station", "Beaumont", "Texarkana", "Shreveport", "Lake Charles",
        "Houma", "Baton Rouge", "Lafayette", "Monroe", "Alexandria", "Huntsville",
        "Mobile", "Montgomery", "Tuscaloosa", "Dothan", "Gadsden", "Anniston",
        "Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro",
        "Jackson", "Little Rock", "Fort Smith", "Fayetteville", "Jonesboro", "Pine Bluff",
        "Shreveport", "Baton Rouge", "New Orleans", "Lafayette", "Lake Charles", "Monroe",
        "Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton", "Edmond",
        "Amarillo", "Lubbock", "Midland", "Odessa", "San Angelo", "Abilene",
        "Wichita", "Topeka", "Lawrence", "Salina", "Manhattan", "Emporia",
        "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton",
        "Pueblo", "Boulder", "Greeley", "Westminster", "Arvada", "Centennial",
        "Albuquerque", "Santa Fe", "Las Cruces", "Rio Rancho", "Roswell", "Alamogordo",
        "Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale", "Glendale",
        "Tempe", "Peoria", "Surprise", "Yuma", "Flagstaff", "Sedona",
        "Las Vegas", "Henderson", "Reno", "Sparks", "Carson City", "Elko",
        "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento",
        "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Santa Ana", "Riverside",
        "Stockton", "Irvine", "Modesto", "Fontana", "Oxnard", "Moreno Valley",
        "Glendale", "Huntington Beach", "Santa Clarita", "Garden Grove", "Oceanside",
        "Rancho Cucamonga", "Ontario", "Santa Rosa", "Elk Grove", "Corona",
        "Lancaster", "Palmdale", "Salinas", "Pomona", "Hayward", "Escondido",
        "Sunnyvale", "Torrance", "Pasadena", "Sunnyvale", "Visalia", "Concord",
        "Victorville", "Santa Clara", "Vallejo", "Berkeley", "El Monte", "Downey",
        "Costa Mesa", "Inglewood", "Carlsbad", "San Buenaventura", "Fairfield", "West Covina",
        "Murrieta", "Richmond", "Norwalk", "Antioch", "Temecula", "Burbank",
        "Daly City", "El Cajon", "San Mateo", "Rialto", "Las Cruces", "Clovis",
        "Jurupa Valley", "Compton", "Vista", "South Gate", "Mission Viejo", "Vacaville",
        "Carson", "Hesperia", "Santa Maria", "Redding", "Santa Barbara", "Elgin",
        "Chico", "San Leandro", "San Marcos", "Whittier", "Tracy", "Lodi",
        "Merced", "Modesto", "Turlock", "Manteca", "Eureka", "Red Bluff",
        "Ukiah", "Yreka", "Crescent City", "Grass Valley", "Truckee", "South Lake Tahoe",
        "Marysville", "Yuba City", "Oroville", "Willows", "Corning", "Redding",
        "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton",
        "Waukesha", "Eau Claire", "Oshkosh", "Janesville", "West Allis", "La Crosse",
        "Sheboygan", "Wauwatosa", "Fond du Lac", "New Berlin", "Wausau", "Brookfield",
        "Greenfield", "Manitowoc", "Neenah", "Menasha", "Fitchburg", "De Pere",
        "Stevens Point", "Appleton", "Oshkosh", "Beloit", "Watertown", "Ripon",
        "Baraboo", "Wisconsin Dells", "Lake Geneva", "Sturgeon Bay", "Antigo", "Merrill",
        "Hayward", "Spooner", "Ashland", "Ironwood", "Rhinelander", "Tomahawk",
        "Minocqua", "Eagle River", "Crandon", "Medford", "Abbotsford", "Colby",
        "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Lansing", "Ann Arbor",
        "Flint", "Dearborn", "Livonia", "Westland", "Troy", "Farmington Hills",
        "Kalamazoo", "Wyoming", "Southfield", "Rochester Hills", "Pontiac", "St. Clair Shores",
        "Royal Oak", "Novi", "Battle Creek", "Saginaw", "Kentwood", "Kalamazoo",
        "Muskegon", "Midland", "Adrian", "Alpena", "Alma", "Ann Arbor",
        "Au Gres", "Bad Axe", "Bay City", "Beaverton", "Belding", "Benton Harbor",
        "Big Rapids", "Birmingham", "Blissfield", "Boyne City", "Cadillac", "Charlotte",
        "Cheboygan", "Coldwater", "Corunna", "Detroit", "Dowagiac", "East Lansing",
        "Eaton Rapids", "Escanaba", "Evart", "Fenton", "Flint", "Gaylord",
        "Gladwin", "Grand Haven", "Grand Rapids", "Grayling", "Greenville", "Hastings",
        "Hillsdale", "Holland", "Houghton", "Howell", "Ionia", "Iron Mountain",
        "Iron River", "Ironwood", "Ishpeming", "Jackson", "Kalamazoo", "Kalkaska",
        "Lansing", "Lapeer", "Ludington", "Mackinaw City", "Manistee", "Marquette",
        "Marysville", "Mason", "Midland", "Mount Clemens", "Mount Pleasant", "Munising",
        "Muskegon", "Negaunee", "Newberry", "Niles", "Norway", "Ontonagon",
        "Owosso", "Petoskey", "Pontiac", "Port Huron", "Portland", "Quincy",
        "Republic", "Roscommon", "Saginaw", "Saint Ignace", "Saint Joseph", "Sault Ste. Marie",
        "Scottville", "South Haven", "Sturgis", "Tawas City", "Traverse City", "Trenton",
        "Valley City", "Wakefield", "Wayland", "West Branch", "Whitehall", "Williamston",
        "Wyandotte", "Ypsilanti", "Zeeland",
    ],
    "GB": [
        "London", "Birmingham", "Manchester", "Glasgow", "Liverpool", "Bristol", "Sheffield",
        "Leeds", "Edinburgh", "Leicester", "Coventry", "Bradford", "Cardiff", "Belfast",
        "Nottingham", "Hull", "Newcastle", "Stoke", "Southampton", "Derby", "Portsmouth",
        "Brighton", "Plymouth", "Reading", "Bournemouth", "Aberdeen", "Middlesbrough",
        "Norwich", "Cambridge", "Oxford", "Swansea", "Bath", "York", "Exeter",
        "Ipswich", "Cheltenham", "Gloucester", "Wolverhampton", "Sunderland", "Blackpool",
        "Bolton", "Bury", "Oldham", "Rochdale", "Stockport", "Telford",
        "Warrington", "Wigan", "Salford", "Solihull", "West Bromwich", "Worcester",
        "Lincoln", "Gloucester", "Hereford", "Shrewsbury", "Chester", "Carlisle",
        "Durham", "Darlington", "Hartlepool", "Scarborough", "Grimsby", "Doncaster",
        "Rotherham", "Barnsley", "Wakefield", "Huddersfield", "Halifax", "Harrogate",
        "Skipton", "Blackburn", "Burnley", "Preston", "Lancaster", "Barrow-in-Furness",
        "Carlisle", "Workington", "Whitehaven", "Keswick", "Penrith", "Ambleside",
        "Windermere", "Kendal", "Loughborough", "Mansfield", "Worksop", "Retford",
        "Newark", "Grantham", "Boston", "Skegness", "Huntingdon", "Peterborough",
        "Ely", "King's Lynn", "Thetford", "Bury St Edmunds", "Sudbury", "Letchworth",
        "Stevenage", "Hertford", "St Albans", "Watford", "Hemel Hempstead", "Luton",
        "Dunstable", "Leighton Buzzard", "Aylesbury", "High Wycombe", "Milton Keynes",
        "Northampton", "Kettering", "Wellingborough", "Corby", "Daventry", "Banbury",
        "Bicester", "Oxford", "Abingdon", "Witney", "Burford", "Chipping Norton",
        "Woodstock", "Henley-on-Thames", "Marlow", "High Wycombe", "Beaconsfield",
        "Maidenhead", "Windsor", "Eton", "Slough", "Bracknell", "Wokingham",
        "Reading", "Newbury", "Hungerford", "Andover", "Tidworth", "Salisbury",
        "Amesbury", "Trowbridge", "Bradford-on-Avon", "Chippenham", "Corsham", "Melksham",
        "Devizes", "Marlborough", "Swindon", "Cirencester", "Stroud", "Dursley",
        "Nailsworth", "Minchinhampton", "Painswick", "Bisley", "Frampton", "Stonehouse",
        "Dursley", "Wotton-under-Edge", "Thornbury", "Bradley Stoke", "Filton", "Patchway",
    ],
    "DE": [
        "Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf",
        "Leipzig", "Dortmund", "Essen", "Bremen", "Dresden", "Hannover", "Nuremberg",
        "Duisburg", "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Munster", "Mannheim",
        "Karlsruhe", "Augsburg", "Wiesbaden", "Monchengladbach", "Gelsenkirchen", "Aachen",
        "Braunschweig", "Kiel", "Chemnitz", "Halle", "Magdeburg", "Freiburg",
        "Krefeld", "Mainz", "Ludwigshafen", "Erfurt", "Oberhausen", "Rostock",
        "Kassel", "Hagen", "Potsdam", "Saarbrucken", "Hamm", "Ludwigsburg",
        "Oldenburg", "Muhlheim", "Osnabruck", "Leverkusen", "Heidelberg", "Darmstadt",
        "Solingen", "Regensburg", "Herne", "Paderborn", "Neuss", "Ingolstadt",
        "Offenbach", "Wurzburg", "Ulm", "Heilbronn", "Pforzheim", "Wolfsburg",
        "Gottingen", "Bottrop", "Reutlingen", "Koblenz", "Bremerhaven", "Erlangen",
        "Bergisch Gladbach", "Remscheid", "Trier", "Jena", "Recklinghausen",
        "Salzgitter", "Moers", "Siegen", "Hildesheim", "Cottbus", "Gera",
        "Witten", "Iserlohn", "Gutersloh", "Schwerin", "Duren", "Ratingen",
        "Lunen", "Konstanz", "Villingen-Schwenningen", "Marl", "Esslingen",
        "Ludwigsburg", "Hanau", "Minden", "Tubingen", "Dorsten", "Marburg",
        "Arnsberg", "Luneburg", "Landshut", "Fulda", "Aalen", "Korbach",
        "Plauen", "Celle", "Detmold", "Norderstedt", "Lemgo", "Passau",
        "Bayreuth", "Cuxhaven", "Friedrichshafen", "Lindau", "Ravensburg",
        "Biberach", "Memmingen", "Kempten", "Augsburg", "Donauworth",
        "Gunzburg", "Krumbach", "Neu-Ulm", "Dillingen", "Lauingen",
        "Nordlingen", "Ansbach", "Rothenburg", "Gunzenhausen", "WeiBenburg",
        "Ingolstadt", "Freising", "Landshut", "Erding", "Dachau",
        "Starnberg", "Furstenfeldbruck", "Garmisch-Partenkirchen", "Murnau",
        "Weilheim", "Penzberg", "Bad Tolz", "Miesbach", "Rosenheim",
        "Traunstein", "Bad Reichenhall", "Berchtesgaden", "Muhldorf",
        "Altotting", "Freilassing", "Salzburg", "Garmisch-Partenkirchen",
        "Oberstdorf", "Fussen", "Marktoberdorf", "Kaufbeuren",
        "Memmingen", "Kempten", "Immenstadt", "Sonthofen", "Oberstdorf",
    ],
    "FR": [
        "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg",
        "Montpellier", "Bordeaux", "Lille", "Rennes", "Reims", "Le Havre",
        "Saint-Etienne", "Toulon", "Le Mans", "Aix-en-Provence", "Brest",
        "Nimes", "Limoges", "Clermont-Ferrand", "Tours", "Amiens", "Metz",
        "Perpignan", "Besancon", "Orleans", "Rouen", "Mulhouse", "Caen",
        "Nancy", "Avignon", "St-Denis", "Montreuil", "Saint-Paul", "Dijon",
        "Angers", "Nantes", "Toulon", "Le Havre", "Grenoble", "Villeurbanne",
        "Clermont-Ferrand", "Toulouse", "Bordeaux", "Lille", "Rennes",
        "Reims", "Toulon", "Saint-Etienne", "Le Havre", "Nimes", "Metz",
        "Perpignan", "Besancon", "Orleans", "Rouen", "Mulhouse", "Caen",
        "Avignon", "Nancy", "Limoges", "Amiens", "Clermont-Ferrand", "Tours",
        "Brest", "Perpignan", "Besancon", "Orleans", "Rouen", "Mulhouse",
        "Caen", "Nancy", "Avignon", "Limoges", "Amiens", "Clermont-Ferrand",
        "Tours", "Brest", "Perpignan", "Besancon", "Orleans", "Rouen",
        "Mulhouse", "Caen", "Nancy", "Avignon", "Limoges", "Amiens",
        "Clermont-Ferrand", "Tours", "Brest", "Perpignan", "Besancon",
        "Orleans", "Rouen", "Mulhouse", "Caen", "Nancy", "Avignon",
        "Limoges", "Amiens", "Clermont-Ferrand", "Tours", "Brest", "Perpignan",
        "Besancon", "Orleans", "Rouen", "Mulhouse", "Caen", "Nancy",
        "Avignon", "Limoges", "Amiens", "Clermont-Ferrand", "Tours", "Brest",
    ],
    "ES": [
        "Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza", "Malaga", "Murcia",
        "Palma", "Las Palmas", "Bilbao", "Alicante", "Cordoba", "Valladolid", "Vigo",
        "Gijon", "Granada", "A Coruna", "Vitoria", "Santa Cruz", "Pamplona",
        "Santander", "Castellon", "Almeria", "San Sebastian", "Burgos", "Salamanca",
        "Huelva", "Logrono", "Badajoz", "Tarragona", "Leon", "Cadiz", "Oviedo",
        "Lerida", "Jaen", "Ourense", "Girona", "Lugo", "Pontevedra",
        "Bilbao", "Barcelona", "Madrid", "Valencia", "Seville", "Zaragoza",
        "Malaga", "Murcia", "Palma", "Las Palmas", "Alicante", "Cordoba",
        "Valladolid", "Vigo", "Gijon", "Granada", "A Coruna", "Vitoria",
        "Pamplona", "Santander", "Castellon", "Almeria", "San Sebastian",
        "Burgos", "Salamanca", "Huelva", "Logrono", "Badajoz", "Tarragona",
        "Leon", "Cadiz", "Oviedo", "Lerida", "Jaen", "Ourense", "Girona",
        "Lugo", "Pontevedra", "Tudela", "Alcala de Henares", "Torrejon de Ardoz",
        "Parla", "Alcobendas", "Leganes", "Getafe", "Alcorcon", "Fuenlabrada",
        "Mostoles", "Pozuelo de Alarcon", "Las Rozas", "Majadahonda",
        "Sant Cugat del Valles", "Terrassa", "Sabadell", "Mataro", "Granollers",
        "Viladecans", "Cornella de Llobregat", "Manresa", "Vic", "Igualada",
        "Sant Feliu de Llobregat", "Castelldefels", "Sitges", "Vendrell",
        "Tarragona", "Reus", "Salou", "Cambrils", "Vinaroz", "Benicarló",
        "Castellon de la Plana", "Villarreal", "Onda", "Almassora", "Benicàssim",
        "Burriana", "Nules", "Segorbe", "Vila-real", "Sagunto", "Gilet",
        "Algemesí", "Alzira", "Carcaixent", "Gandia", "Oliva", "Pego",
        "Denia", "Javea", "Calpe", "Altea", "Benidorm", "Villajoyosa",
        "Alcoy", "Ontinyent", "Xàtiva", "Játiva", "Bocairent", "Enguera",
        "Carlet", "Sueca", "Cullera", "Tavernes", "Gandía", "Daimús",
    ],
    "IT": [
        "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna",
        "Florence", "Catania", "Venice", "Verona", "Messina", "Padua", "Trieste",
        "Brescia", "Taranto", "Prato", "Modena", "Reggio Calabria", "Perugia",
        "Cagliari", "Livorno", "Parma", "Foggia", "Reggio Emilia", "Ancona",
        "Campobasso", "Catanzaro", "Pescara", "Lecce", "Ferrara", "Udine",
        "Sassari", "Syracuse", "Monza", "Bergamo", "Piacenza", "Ancona",
        "Lucca", "Bolzano", "Vicenza", "Trento", "Pisa", "Como",
        "Lecce", "Bari", "Taranto", "Brindisi", "Foggia", "Barletta",
        "Andria", "Trani", "Bitonto", "Altamura", "Matera", "Gravina",
        "Corato", "Putignano", "Conversano", "Polignano", "Monopoli",
        "Ostuni", "Fasano", "Cisternino", "Martina Franca", "Taranto",
        "Francavilla", "Squinzano", "Mesagne", "Oria", "San Vito",
        "Lecce", "Gallipoli", "Galatina", "Copertino", "Nardo",
        "Castrignano", "Gallipoli", "Porto Cesareo", "Torre dell'Orso",
        "Santa Maria", "Lido", "Lecce", "Maglie", "Otranto",
        "Santa Cesarea", "Tricase", "Ugento", "Alessano", "Specchia",
        "Ruffano", "Melpignano", "Muro Leccese", "Bagnolo", "Corigliano",
    ],
    "PT": [
        "Lisbon", "Porto", "Faro", "Braga", "Coimbra", "Funchal", "Setubal",
        "Evora", "Leiria", "Aveiro", "Viseu", "Viana do Castelo", "Guarda",
        "Castelo Branco", "Portalegre", "Santarem", "Beja", "Evora",
        "Braganca", "Vila Real", "Lamego", "Viseu", "Aveiro", "Ovar",
        "Espinho", "Oliveira de Azemeis", "Santa Maria da Feira", "Agueda",
        "Mealhada", "Mortagua", "Tondela", "Nelas", "Viseu", "Lamego",
        "Armamar", "Tabuaco", "Mesao Frio", "Santa Marta", "Baião",
        "Marco de Canaveses", "Penafiel", "Lousada", "Pacos de Ferreira",
        "Santo Tirso", "Trofa", "Vila Nova de Gaia", "Gondomar",
        "Matosinhos", "Maia", "Valongo", "Ermesinde", "Rio Tinto",
        "Camara de Lobos", "Funchal", "Caniaco", "Caniçal", "Machico",
        "Santo da Serra", "São Pedro", "Faial", "Santana", "Ribeira Brava",
        "Câmara de Lobos", "Ponta do Sol", "Calheta", "Porto Moniz",
        "São Vicente", "Ribeira Grande", "Vila do Porto", "Povoação",
        "Nordeste", "Lagoa", "Faro", "Loulé", "Olhão", "Tavira",
        "Lagos", "Portimão", "Silves", "Albufeira", "Louletão",
        "Vila Real de Santo António", "Castro Marim", "Alcoutim",
        "Monchique", "São Brás de Alportel", "Ferreira do Alentejo",
        "Cuba", "Beja", "Moura", "Serpa", "Mértola", "Odemira",
        "Aljezur", "Lagos", "Sagres", "Vila do Bispo", "Lajes",
    ],
    "RO": [
        "Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta", "Craiova",
        "Brasov", "Galati", "Ploiesti", "Oradea", "Braila", "Arad", "Pitesti",
        "Sibiu", "Bacau", "Targu Mures", "Baia Mare", "Buzau", "Botosani",
        "Satu Mare", "Râmnicu Valcea", "Piatra Neamt", "Drobeta-Turnu Severin",
        "Târgu Jiu", "Focsani", "Bistrita", "Slobozia", "Deva", "Hunedoara",
        "Slatina", "Turda", "Resita", "Tulcea", "Sfantu Gheorghe", "Miercurea Ciuc",
        "Sighisoara", "Medias", "Sebes", "Alba Iulia", "Blaj", "Lugoj",
        "Caransebes", "Orastie", "Hațeg", "Petroșani", "Lupeni", "Uricani",
        "Aninoasa", "Târgu Cărbunești", "Turceni", "Rovinari", "Bumbesti-Jiu",
        "Luduș", "Câmpia Turzii", "Gherla", "Dej", "Beclean", "Nasaud",
        "Zalau", "Satu Mare", "Carei", "Negresti-Oaș", "Tasnad", "Simleu",
        "Oradea", "Salonta", "Beius", "Steiu", "Alesd", "Nucet",
        "Valea lui Mihai", "Săcueni", "Marghita", "Aleșd", "Tileagd",
        "Brad", "Cimpeni", "Câmpeni", "Zlatna", "Abrud", "Baia de Aries",
        "Aiud", "Unirea", "Teius", "Ocna Mures", "Ludus", "Iernut",
        "Sighisoara", "Dumbraveni", "Saschiz", "Cristian", "Bunesti",
    ],
    "PL": [
        "Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin",
        "Bydgoszcz", "Lublin", "Katowice", "Bialystok", "Gdynia", "Czestochowa",
        "Radom", "Torun", "Sosnowiec", "Rzeszow", "Kielce", "Gliwice",
        "Olsztyn", "Zabrze", "Bielsko-Biala", "Bytom", "Zielona Gora",
        "Rybnik", "Ruda Slaska", "Opole", "Tychy", "Gorzow Wielkopolski",
        "Elblag", "Plock", "Walbrzych", "Wloclawek", "Tarnow", "Chorzow",
        "Kalisz", "Legnica", "Koszalin", "Piła", "Inowroclaw", "Lubin",
        "Ostrowiec Swietokrzyski", "Gniezno", "Stargard", "Glogow", "Ostrow Wielkopolski",
        "Zambrów", "Malbork", "Przemysl", "Zamość", "Leszno", "Nysa",
        "Mysłowice", "Cieszyn", "Oświęcim", "Legionowo", "Wejherowo", "Piaseczno",
        "Otwock", "Marki", "Ząbki", "Wołomin", "Kobyłka", "Janki",
        "Pruszków", "Grodzisk Mazowiecki", "Sochaczew", "Żyrardów", "Milanówek",
        "Podkowa Leśna", "Grodzisk Wielkopolski", "Nowy Tomyśl", "Wolsztyn",
        "Buk", "Opalenica", "Stęszew", "Mosina", "Kórnik", "Puszczykowo",
        "Lusowo", "Tarnowo Podgórne", "Dopiewo", "Komorniki", "Gmina",
        "Luboń", "Swarzędz", "Czerwonak", "Murowana Goślina", "Pobiedziska",
    ],
    "UA": [
        "Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Zaporizhzhia", "Lviv",
        "Mykolaiv", "Luhansk", "Vinnytsia", "Simferopol", "Kherson", "Poltava",
        "Chernihiv", "Cherkasy", "Sumy", "Zhytomyr", "Khmelnytskyi", "Rivne",
        "Ivano-Frankivsk", "Ternopil", "Lutsk", "Bila Tserkva", "Kramatorsk",
        "Melitopol", "Nikopol", "Sloviansk", "Berdiansk", "Uzhhorod",
        "Kamianets-Podilskyi", "Kovel", "Konotop", "Mukachevo", "Pavlohrad",
        "Kamianske", "Kostiantynivka", "Kramatorsk", "Druzhkivka", "Pokrovsk",
        "Bakhmut", "Sloviansk", "Toretsk", "Marinka", "Avdiivka", "Marinka",
        "Vuhledar", "Kurakhove", "Chasiv Yar", "Siversk", "Lyman",
        "Izium", "Barvinkove", "Krasnohorivka", "Staromykhailivka",
        "Novomykhailivka", "Prechystivka", "Velyka Novosilka", "Vremivka",
        "Storozheve", "Blahodatne", "Nesterianka", "Shevchenko",
        "Zaporizhzhia", "Orikhiv", "Huliaipole", "Polohy", "Biloberizhzhia",
        "Kamianske", "Dnipro", "Pavlohrad", "Synelnykove", "Piatykhatky",
        "Vilnohirsk", "Verkhivtseve", "Shyroke", "Auly", "Lozova",
        "Perevalsk", "Alchevsk", "Kadiivka", "Stakhanov", "Brianka",
        "Sievierodonetsk", "Lysychansk", "Rubizhne", "Popasna", "Hirske",
        "Zolote", "Kremmina", "Svatove", "Starobilsk", "Bilokurakyne",
    ],
    "RU": [
        "Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan",
        "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don",
        "Ufa", "Krasnoyarsk", "Voronezh", "Perm", "Volgograd", "Krasnodar",
        "Saratov", "Tyumen", "Tolyatti", "Izhevsk", "Barnaul", "Irkutsk",
        "Vladivostok", "Khabarovsk", "Yaroslavl", "Ulyanovsk", "Ivanovo",
        "Kemerovo", "Vladimir", "Orenburg", "Tomsk", "Kursk", "Murmansk",
        "Pskov", "Smolensk", "Kostroma", "Kaliningrad", "Astrakhan", "Ryazan",
        "Tula", "Tver", "Lipetsk", "Penza", "Nizhny Tagil", "Kirov",
        "Cheboksary", "Bryansk", "Magnitogorsk", "Kaluga", "Sochi", "Orel",
        "Kurgan", "Vladikavkaz", "Makhachkala", "Nalchik", "Yoshkar-Ola",
        "Kizlyar", "Derbent", "Kaspiysk", "Buynaksk", "Kizlyar", "Grozny",
        "Urus-Martan", "Shali", "Argun", "Gudermes", "Novaya Ladoga",
        "Volkhov", "Tikhvin", "Podporozhye", "Lodeynoye Pole", "Kingisepp",
        "Ivangorod", "Sosnovy Bor", "Kudrovo", "Murino", "Vsevolozhsk",
        "Aprelevka", "Krasnoznamensk", "Vnukovo", "Troitsk", "Shcherbinka",
        "Kommunarka", "Moskovsky", "Voskhod", "Molodjozhny", "Rogovo",
    ],
    "MD": [
        "Chisinau", "Tiraspol", "Balti", "Bender", "Cahul", "Ungheni", "Soroca",
        "Orhei", "Comrat", "Edinet", "Drochia", "Glodeni", "Hincesti", "Ialoveni",
        "Leova", "Nisporeni", "Rezina", "Riscani", "Singerei", "Soldanesti",
        "Stefan-Voda", "Straseni", "Telenesti", "Floresti", "Donduseni",
        "Cimislia", "Anenii Noi", "Cantemir", "Calarasi", "Criuleni",
        "Dубэсарь", "Taraclia", "Basarabeasca", "Ust-Dniester",
        "Briceni", "Drochia", "Balti", "Orhei", "Ungheni", "Cahul",
        "Soroca", "Edinet", "Hincesti", "Ialoveni", "Straseni",
    ],
    "TR": [
        "Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana", "Konya",
        "Gaziantep", "Mersin", "Kayseri", "Eskisehir", "Diyarbakir", "Samsun",
        "Denizli", "Sanliurfa", "Malatya", "Kahramanmaras", "Mugla", "Tekirdag",
        "Trabzon", "Manisa", "Hatay", "Balikesir", "Van", "Aydin", "Isparta",
        "Batman", "Zonguldak", "Tokat", "Sakarya", "Edirne", "Kirikkale",
        "Adiyaman", "Izmit", "Osmaniye", "Duzce", "Corum", "Bolu",
        "Elazig", "Canakkale", "Nigde", "Kutahya", "Bingol", "Karaman",
        "Agri", "Tunceli", "Giresun", "Rize", "Gumushane", "Bayburt",
        "Artvin", "Kars", "Ardahan", "Igdir", "Sinop", "Kastamonu",
        "Bartin", "Karabuk", "Amasya", "Sivas", "Yozgat", "Kirsehir",
        "Nevsehir", "Aksaray", "Kirsehir", "Cankiri", "Kastamonu",
        "Bartin", "Zonguldak", "Karadeniz Eregli", "Duzce", "Bolu",
        "Istanbul", "Ankara", "Izmir", "Bursa", "Antalya", "Adana",
    ],
    "CA": [
        "Toronto", "Montreal", "Vancouver", "Calgary", "Edmonton", "Ottawa",
        "Winnipeg", "Quebec City", "Hamilton", "Kitchener", "London Ontario",
        "Halifax", "Victoria", "Oshawa", "Windsor", "Saskatoon", "Regina",
        "St. John's", "Barrie", "Kelowna", "Abbotsford", "Kelowna",
        "Kamloops", "Nanaimo", "Prince George", "Chilliwack", "Vernon",
        "Penticton", "Cranbrook", "Nelson", "Trail", "Castlegar",
        "Revelstoke", "Golden", "Fernie", "Invermere", "Radium Hot Springs",
        "Canmore", "Banff", "Jasper", "Hinton", "Edson", "Whitecourt",
        "Grande Prairie", "Peace River", "High Level", "Fort McMurray",
        "Lac La Biche", "Cold Lake", "Bonnyville", "St. Paul", "Vegreville",
        "Vermilion", "Kitscoty", "Mayerthorpe", "Westlock", "Barrhead",
        "Spruce Grove", "Stony Plain", "Morinville", "Leduc", "Wetaskiwin",
        "Ponoka", "Rimbey", "Ponoka", "Bentley", "Gull Lake", "Rimbey",
        "Blindman", "Blackfalds", "Lacombe", "Mirror", "Rycroft",
        "Spirit River", "Sexsmith", "Wembley", "Beaverlodge", "Hythe",
        "Grimshaw", "Nampa", "Girouxville", "Manoir", "Falher", "Donnelly",
    ],
    "AU": [
        "Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Gold Coast",
        "Newcastle", "Canberra", "Wollongong", "Logan", "Hobart", "Geelong",
        "Townsville", "Cairns", "Darwin", "Toowoomba", "Ballarat", "Bendigo",
        "Launceston", "Mackay", "Rockhampton", "Bundaberg", "Hervey Bay",
        "Wagga Wagga", "Albury", "Wodonga", "Mildura", "Shepparton",
        "Dubbo", "Tamworth", "Orange", "Bathurst", "Wagga Wagga",
        "Coffs Harbour", "Port Macquarie", "Lismore", "Byron Bay",
        "Ballina", "Murwillumbah", "Kyogle", "Casino", "Grafton",
        "Coffs Harbour", "Sawtell", "Bellingen", "Dorrigo", "Armidale",
        "Tamworth", "Narrabri", "Moree", "Inverell", "Tenterfield",
        "Glen Innes", "Armidale", "Uralla", "Walcha", "Werris Creek",
        "Quirindi", "Murrurundi", "Muswellbrook", "Denman", "Merriwa",
        "Singleton", "Cessnock", "Maitland", "Lorn", "Clarence Town",
        "Dungog", "Paterson", "Vacy", "Broke", "Jerrys Plains",
        "Broke", "Fordwich", "Lakesland", "Darlington", "Wollombi",
        "Congewai", "Cessnock", "Nulkaba", "Kitchener", "Stanford",
    ],
    "BR": [
        "Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza",
        "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre",
        "Belem", "Goiania", "Guarulhos", "Campinas", "Sao Luis", "Maceio",
        "Campo Grande", "Teresina", "Sao Bernardo do Campo", "Nova Iguacu",
        "Duque de Caxias", "Sao Joao de Meriti", "Natal", "Osasco",
        "Jundiai", "Santo Andre", "Sao Jose dos Campos", "Ribeirao Preto",
        "Uberlandia", "Sorocaba", "Contagem", "Aracaju", "Feira de Santana",
        "Cuiaba", "Joinville", "Juiz de Fora", "Londrina", "Niteroi",
        "Ananindeua", "Santos", "Maua", "Sao Jose do Rio Preto",
        "Mogi das Cruzes", "Diadema", "Betim", "Jaboatao", "Sao Bernardo",
        "Campos dos Goytacazes", "Bauru", "Vitoria", "Porto Velho",
        "Serra", "Macapa", "Natal", "Teresina", "Uberaba", "Caxias do Sul",
        "Ponta Grossa", "Belen", "Sao Joao del Rei", "Alfenas",
        "Varginha", "Poços de Caldas", "Passos", "Itajuba", "Santa Rita",
        "Belo Horizonte", "Sete Lagoas", "Contagem", "Betim", "Ibirité",
        "Ribeirão das Neves", "Betim", "Contagem", "Santa Luzia",
        "Ipatinga", "Governador Valadares", "Caratinga", "Timóteo",
        "Coronel Fabriciano", "Aimorés", "Conselheiro Pena", "Resplendor",
        "Itambacuri", "Tumiritinga", "Campanario", "Engenheiro Caldas",
    ],
    "MX": [
        "Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana",
        "Leon", "Ciudad Juarez", "Zapopan", "Merida", "San Luis Potosi",
        "Aguascalientes", "Chihuahua", "Queretaro", "Morelia", "Hermosillo",
        "Saltillo", "Veracruz", "Toluca", "Cancun", "Acapulco",
        "Oaxaca", "Pachuca", "Tampico", "Campeche", "Villahermosa",
        "Tuxtla Gutierrez", "Cuernavaca", "Durango", "Mazatlan", "Tepic",
        "La Paz", "Ensenada", "Culiacan", "Zacatecas", "San Cristobal",
        "Cuautla", "Jiutepec", "Temixco", "Yautepec", "Cuautla",
        "Ciudad Valles", "Tampico", "Madero", "Altamira", "Ciudad Madero",
        "Tampico", "Madero", "Altamira", "Ciudad Madero", "San Fernando",
        "Soto la Marina", "Mante", "Ciudad Madero", "Tampico",
        "Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Tlajomulco",
        "El Salto", "Guadalajara", "Tlaquepaque", "Tonalá", "Tlajomulco",
        "Villa del Carbon", "Nicolas Romero", "Jilotzingo", "Tepotzotlan",
        "Cuautitlan Izcalli", "Coacalco", "Tecamac", "Teotihuacan",
        "Acolman", "Pachuca", "Real del Monte", "Huasca", "Mineral del Monte",
        "Omitlan", "Zempoala", "Actopan", "Mixquiahuala", "Tula de Allende",
        "Tepeji", "Atotonilco", "Tulancingo", "Cuautepec", "San Agustin",
    ],
    "IN": [
        "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai",
        "Kolkata", "Pune", "Jaipur", "Lucknow", "Kanpur", "Nagpur",
        "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad",
        "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik",
        "Faridabad", "Meerut", "Rajkot", "Varanasi", "Srinagar", "Aurangabad",
        "Dhanbad", "Amritsar", "Allahabad", "Ranchi", "Howrah", "Coimbatore",
        "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur",
        "Kochi", "Chandigarh", "Thiruvananthapuram", "Dehradun", "Lucknow",
        "Noida", "Nagpur", "Bhopal", "Patna", "Indore", "Vadodara",
        "Bhopal", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut",
        "Rajkot", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar",
        "Allahabad", "Ranchi", "Howrah", "Coimbatore", "Jabalpur", "Gwalior",
        "Vijayawada", "Jodhpur", "Madurai", "Raipur", "Kochi", "Chandigarh",
        "Thiruvananthapuram", "Dehradun", "Haridwar", "Rishikesh", "Mussoorie",
        "Nainital", "Almora", "Pithoragarh", "Champawat", "Udham Singh Nagar",
        "Haldwani", "Kathgodam", "Ranikhet", "Bageshwar", "Chamoli",
        "Uttarkashi", "Pauri", "Tehri", "Dehradun", "Doiwala", "Rishikesh",
        "Doon", "Vikasnagar", "Sahastradhara", "Malsi", "Selaqui",
    ],
    "CN": [
        "Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Hangzhou",
        "Wuhan", "Xi'an", "Nanjing", "Chongqing", "Tianjin", "Suzhou",
        "Shenyang", "Harbin", "Qingdao", "Dalian", "Zhengzhou", "Jinan",
        "Kunming", "Changsha", "Fuzhou", "Xiamen", "Ningbo", "Wenzhou",
        "Changchun", "Hefei", "Urumqi", "Nanning", "Guiyang", "Taiyuan",
        "Lanzhou", "Haikou", "Hohhot", "Yinchuan", "Xining", "Lhasa",
        "Shenzhen", "Dongguan", "Foshan", "Ningbo", "Wenzhou", "Wuxi",
        "Changzhou", "Xuzhou", "Nantong", "Yangzhou", "Taizhou", "Zhenjiang",
        "Lianyungang", "Huai'an", "Yancheng", "Suqian", "Huaian", "Nanjing",
        "Zhenjiang", "Changzhou", "Wuxi", "Suzhou", "Kunshan", "Changshu",
        "Taicang", "Zhangjiagang", "Haimen", "Rudong", "Qidong", "Nantong",
        "Rugao", "Hai'an", "Dongtai", "Yandeng", "Funing", "Sheyang",
        "Bianbu", "Xinghua", "Jiangyan", "Taizhou", "Jingjiang", "Taixing",
        "Qingdao", "Jinan", "Yantai", "Weifang", "Zibo", "Rizhao",
        "Weihai", "Linyi", "Jining", "Tai'an", "Heze", "Liaocheng",
        "Binzhou", "Dezhou", "Dongying", "Penglai", "Longkou", "Laixi",
        "Jimo", "Pingdu", "Laizhou", "Zhaoyuan", "Longgang", "Qingdao",
    ],
    "JP": [
        "Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Fukuoka",
        "Kobe", "Kyoto", "Hiroshima", "Sendai", "Kitakyushu", "Sakai",
        "Niigata", "Hamamatsu", "Shizuoka", "Sagamihara", "Okayama",
        "Kawasaki", "Kumamoto", "Saitama", "Shimonoseki", "Kagoshima",
        "Funabashi", "Hachioji", "Kawaguchi", "Himeji", "Matsuyama",
        "Utsunomiya", "Matsudo", "Nishinomiya", "Ichikawa", "Kanazawa",
        "Nara", "Oita", "Takatsuki", "Nagasaki", "Toyama", "Gifu",
        "Machida", "Miyazaki", "Toyonaka", "Nagano", "Toyohashi",
        "Toyama", "Suita", "Takasaki", "Okazaki", "Wakayama", "Naha",
        "Kochi", "Tokushima", "Fukui", "Morioka", "Akita", "Yamagata",
        "Fukushima", "Niigata", "Toyama", "Ishikawa", "Fukui", "Yamanashi",
        "Nagano", "Gifu", "Shizuoka", "Aichi", "Mie", "Shiga", "Kyoto",
        "Osaka", "Hyogo", "Nara", "Wakayama", "Tottori", "Shimane",
        "Okayama", "Hiroshima", "Yamaguchi", "Tokushima", "Kagawa",
        "Ehime", "Kochi", "Fukuoka", "Saga", "Nagasaki", "Kumamoto",
        "Oita", "Miyazaki", "Kagoshima", "Okinawa", "Hokkaido",
    ],
    "KR": [
        "Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju",
        "Ulsan", "Suwon", "Changwon", "Seongnam", "Goyang", "Yongin",
        "Cheongju", "Ansan", "Jeonju", "Cheonan", "Anyang", "Pohang",
        "Uijeongbu", "Siheung", "Jeju", "Gimhae", "Gumi", "Gunpo",
        "Yangju", "Paju", "Gimpo", "Hanam", "Anseong", "Pyeongtaek",
        "Osan", "Seosan", "Cheonan", "Asan", "Gongju", "Buyeo",
        "Boryeong", "Taean", "Seocheon", "Gunsan", "Iksan", "Jeongeup",
        "Gochang", "Buan", "Sunchang", "Muju", "Jangsu", "Imsil",
        "Namwon", "Gurye", "Suncheon", "Yeosu", "Mokpo", "Muan",
        "Shinan", "Haenam", "Jindo", "Wando", "Boseong", "Damyang",
        "Hampyeong", "Yeongam", "Mokpo", "Naju", "Hwasun", "Gwangyang",
    ],
    "TH": [
        "Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nonthaburi",
        "Khon Kaen", "Hat Yai", "Udon Thani", "Chiang Rai", "Nakhon Ratchasima",
        "Nakhon Si Thammarat", "Ubon Ratchathani", "Pak Kret", "Khlong Luang",
        "Chon Buri", "Rayong", "Lampang", "Nan", "Mae Hong Son",
        "Tak", "Kamphaeng Phet", "Sukhothai", "Phitsanulok", "Nakhon Sawan",
        "Uttaradit", "Phetchabun", "Loei", "Nong Khai", "Sakon Nakhon",
        "Nakhon Phanom", "Mukdahan", "Amnat Charoen", "Yasothon",
        "Chaiyaphum", "Nakhon Ratchasima", "Buriram", "Surin", "Sisaket",
        "Surat Thani", "Ranong", "Chumphon", "Prachuap Khiri Khan",
        "Phetchaburi", "Ratchaburi", "Kanchanaburi", "Suphan Buri",
        "Sing Buri", "Lop Buri", "Ang Thong", "Ayutthaya", "Pathum Thani",
        "Nonthaburi", "Bangkok", "Nakhon Pathom", "Samut Sakhon",
        "Samut Songkhram", "Phra Nakhon Si Ayutthaya", "Chachoengsao",
        "Prachin Buri", "Sa Kaeo", "Chanthaburi", "Trat", "Rayong",
        "Chon Buri", "Bangkok", "Pattaya", "Phuket", "Krabi",
        "Trang", "Phatthalung", "Songkhla", "Pattani", "Yala",
        "Narathiwat", "Satun",
    ],
    "VN": [
        "Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho",
        "Nha Trang", "Hue", "Da Lat", "Vung Tau", "Bien Hoa",
        "Buon Ma Thuot", "Quy Nhon", "Nam Dinh", "Viet Tri", "Thai Nguyen",
        "Long Xuyen", "My Tho", "Phan Thiet", "Cam Ranh", "Phu Quoc",
        "Dong Hoi", "Quang Ngai", "Tam Ky", "Quang Nam", "Hoi An",
        "Hue", "Dong Ha", "Quang Tri", "Lao Cai", "Sapa",
        "Ha Giang", "Cao Bang", "Lang Son", "Bac Kan", "Thai Nguyen",
        "Bac Giang", "Bac Ninh", "Hai Duong", "Hai Phong", "Hung Yen",
        "Hoa Binh", "Son La", "Dien Bien", "Lai Chau", "Yen Bai",
        "Phu Tho", "Tuyen Quang", "Lao Cai", "Ha Giang", "Cao Bang",
        "Lang Son", "Bac Kan", "Thai Nguyen", "Bac Giang", "Bac Ninh",
    ],
    "PH": [
        "Manila", "Quezon City", "Davao", "Cebu", "Zamboanga", "Taguig",
        "Antipolo", "Pasig", "Cagayan de Oro", "Parañaque", "Dasmariñas",
        "Valenzuela", "Bacoor", "General Santos", "Makati", "Las Piñas",
        "Bacolod", "Muntinlupa", "Iloilo", "Baguio", "Calamba", "Angeles",
        "Olongapo", "Tarlac", "Tacloban", "Lucena", "Butuan", "Iligan",
        "Tuguegarao", "Vigan", "Laoag", "Legazpi", "Puerto Princesa",
        "Tagbilaran", "Dumaguete", "Bacolod", "Iloilo", "Roxas",
        "Kalibo", "Boracay", "Caticlan", "Malay", "Nabas",
        "Libacao", "Banga", "New Washington", "Makato", "Balete",
        "Batan", "Buruanga", "Culasi", "Sebaste", "Tibiao",
        "Pandan", "Culasi", "Hamtic", "San Joaquin", "Miagao",
        "Tigbauan", "Guimbal", "Oton", "Santa Barbara", "Pavia",
        "Leganes", "Lezo", "Nueva Valencia", "San Rafael", "Dumalag",
    ],
    "ID": [
        "Jakarta", "Surabaya", "Bandung", "Medan", "Semarang", "Makassar",
        "Palembang", "Tangerang", "Depok", "Padang", "Denpasar", "Malang",
        "Bekasi", "Manado", "Bogor", "Yogyakarta", "Pekanbaru", "Banjarmasin",
        "Serang", "Cilegon", "Balikpapan", "Pontianak", "Mataram",
        "Yogyakarta", "Kupang", "Jambi", "Samarinda", "Bengkulu",
        "Pematangsiantar", "Bukittinggi", "Langsa", "Lhokseumawe",
        "Tebing Tinggi", "Binjai", "Padangsidimpuan", "Gunungsitoli",
        "Sungai Penuh", "Solok", "Bukittinggi", "Payakumbuh", "Padang Panjang",
        "Sawahlunto", "Pariaman", "Lubuklinggau", "Prabumulih", "Pagar Alam",
        "Metro", "Bandar Lampung", "Pringsewu", "Tanggamus", "Lampung Barat",
        "Tulang Bawang", "Way Kanan", "Lampung Timur", "Lampung Tengah",
    ],
    "MY": [
        "Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Malacca",
        "Kota Kinabalu", "Kuching", "Shah Alam", "Petaling Jaya",
        "Subang Jaya", "Kuantan", "Kota Bharu", "Kuala Terengganu",
        "Alor Setar", "Seremban", "Bintulu", "Miri", "Sandakan",
        "Tawau", "Kluang", "Batu Pahat", "Muar", "Pontian", "Kluang",
        "Segamat", "Kota Tinggi", "Mersing", "Kulai", "Iskandar Puteri",
        "Larkin", "Tebrau", "Johor Jaya", "Plentong", "Pasir Gudang",
        "Masai", "Ulu Tiram", "Sedenak", "Ayer Hitam", "Yong Peng",
        "Bukit Gambir", "Ledang", "Tangkak", "Muadzam Shah", "Pekan",
        "Rompin", "Mersing", "Kuantan", "Gambang", "Bera",
        "Temerloh", "Jerantut", "Cameron Highlands", "Lipis", "Raub",
        "Bentong", "Bukit Tinggi", "Genting Highlands", "Fraser's Hill",
        "Kuala Kubu Bharu", "Rawang", "Selayang", "Batu Caves",
        "Sungai Buloh", "Shah Alam", "Petaling Jaya", "Subang Jaya",
        "Puchong", "Cyberjaya", "Putrajaya", "Sepang", "KLIA",
    ],
    "SG": ["Singapore"],
    "NZ": [
        "Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga",
        "Napier", "Dunedin", "Palmerston North", "Nelson", "Rotorua",
        "New Plymouth", "Whangarei", "Invercargill", "Whanganui",
        "Gisborne", "Timaru", "Otago", "Queenstown", "Taupo",
        "Whakatane", "Cambridge", "Taupo", "Matamata", "Te Awamutu",
        "Ngaruawahia", "Huntly", "Tokoroa", "Putaruru", "Morrinsville",
        "Te Aroha", "Paeroa", "Waihi", "Katikati", "Omokoroa",
        "Mount Maunganui", "Papamoa", "Te Puke", "Kawerau", "Opotiki",
        "Gisborne", "Wairoa", "Napier", "Hastings", "Taradale",
        "Havelock North", "Waipukurau", "Takapau", "Dannevirke",
        "Woodville", "Pahiatua", "Eketahuna", "Masterton", "Carterton",
        "Greytown", "Featherston", "Martinborough", "Palliser Ridge",
    ],
    "ZA": [
        "Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth",
        "Bloemfontein", "Pietermaritzburg", "East London", "Rustenburg",
        "Soweto", "Vereeniging", "Witbank", "Centurion", "Uitenhage",
        "Nelspruit", "Newcastle", "Krugersdorp", "Polokwane", "Kimberley",
        "Richards Bay", "Stellenbosch", "Paarl", "George", "Mossel Bay",
        "Oudtshoorn", "Graaff-Reinet", "Middelburg", "Springbok",
        "Upington", "De Aar", "Colesberg", "Kimberley", "Bloemfontein",
        "Welkom", "Bethlehem", "Harrismith", "Ladysmith", "Dundee",
        "Newcastle", "Limpopo", "Polokwane", "Thohoyandou", "Tzaneen",
        "Mokopane", "Mogalakwena", "Bela-Bela", "Modimolle", "Mookgophong",
    ],
    "EG": [
        "Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Sharm El Sheikh",
        "Hurghada", "Suez", "Port Said", "Ismailia", "Mansoura", "Tanta",
        "Asyut", "Zagazig", "Damietta", "Damanhur", "Minya", "Fayoum",
        "Beni Suef", "Sohag", "Qena", "Marsa Matrouh", "Siwa Oasis",
        "Alexandria", "Cairo", "Giza", "Luxor", "Aswan", "Sharm El Sheikh",
        "Hurghada", "Suez", "Port Said", "Ismailia", "Mansoura", "Tanta",
    ],
    "NG": [
        "Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City",
        "Kaduna", "Jos", "Ilorin", "Oyo", "Enugu", "Abeokuta", "Onitsha",
        "Warri", "Calabar", "Uyo", "Owerri", "Sokoto", "Maiduguri",
        "Zaria", "Aba", "Osogbo", "Ogbomoso", "Makurdi", "Akure",
        "Bauchi", "Ondo", "Ekiti", "Lafia", "Asaba", "Yola",
        "Birnin Kebbi", "Gusau", "Dutse", "Damaturu", "Gombe",
        "Jalingo", "Makurdi", "Lokoja", "Idah", "Nsukka",
    ],
    "KE": [
        "Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika",
        "Malindi", "Kitale", "Garissa", "Kakamega", "Kericho", "Nyeri",
        "Machakos", "Meru", "Embu", "Nanyuki", "Naivasha", "Kilifi",
        "Lamu", "Isiolo", "Marsabit", "Mandera", "Wajir", "Dadaab",
    ],
    "GH": [
        "Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast", "Tema",
        "Obuasi", "Ho", "Sunyani", "Koforidua", "Techiman", "Wa",
        "Bolgatanga", "Teshie", "Madina", "Ashaiman", "Nungua",
        "Teshie", "Nungua", "Kasoa", "Winneba", "Saltpond", "Mankessim",
    ],
    "IL": [
        "Tel Aviv", "Jerusalem", "Haifa", "Rishon LeZion", "Petah Tikva",
        "Ashdod", "Netanya", "Beer Sheva", "Holon", "Bnei Brak",
        "Ramat Gan", "Bat Yam", "Ashkelon", "Herzliya", "Kfar Saba",
        "Hadera", "Nazareth", "Eilat", "Tiberias", "Safed",
    ],
    "SE": [
        "Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras",
        "Orebro", "Linkoping", "Helsingborg", "Jonkoping", "Norrkoping",
        "Lund", "Umea", "Gavle", "Boras", "Sodertalje", "Eskilstuna",
        "Halmstad", "Vaxjo", "Karlstad", "Sundsvall", "Ostersund",
        "Trollhattan", "Lulea", "Kalmar", "Falun", "Gavle",
        "Skelleftea", "Sundsvall", "Harnosand", "Umea", "Pitea",
        "Boden", "Gallivare", "Kiruna", "Malmo", "Lund", "Helsingborg",
    ],
    "NO": [
        "Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen", "Fredrikstad",
        "Kristiansand", "Tromso", "Sandnes", "Sarpsborg", "Skien",
        "Alesund", "Sandefjord", "Haugesund", "Tonsberg", "Moss",
        "Porsgrunn", "Hamar", "Kristiansund", "Lillehammer", "Molde",
        "Bodo", "Narvik", "Harstad", "Alta", "Hammerfest",
        "Vadso", "Kirkenes", "Svalbard", "Longyearbyen",
    ],
    "DK": [
        "Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg", "Randers",
        "Kolding", "Horsens", "Vejle", "Roskilde", "Herning", "Silkeborg",
        "Næstved", "Fredericia", "Viborg", "Køge", "Holstebro", "Slagelse",
        "Hillerød", "Helsingør", "Skagen", "Frederikshavn", "Svendborg",
        "Nykøbing Falster", "Næstved", "Ringsted", "Holbæk", "Kalundborg",
    ],
    "FI": [
        "Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu", "Turku",
        "Jyvaskyla", "Lahti", "Kuopio", "Pori", "Kajaani", "Joensuu",
        "Lappeenranta", "Hameenlinna", "Vaasa", "Seinajoki", "Rovaniemi",
        "Kemi", "Tornio", "Oulu", "Raahe", "Kalajoki", "Rahja",
        "Jakobstad", "Kristinestad", "Närpes", "Malax", "Korsnas",
    ],
    "NL": [
        "Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven",
        "Tilburg", "Groningen", "Almere", "Breda", "Nijmegen", "Haarlem",
        "Arnhem", "Enschede", "Apeldoorn", "Amersfoort", "Zaanstad",
        "Maastricht", "Leiden", "Dordrecht", "Zoetermeer", "Zwolle",
        "Deventer", "Delft", "Alkmaar", "Heerlen", "Venlo", "Leeuwarden",
    ],
    "BE": [
        "Brussels", "Antwerp", "Ghent", "Bruges", "Liege", "Leuven",
        "Namur", "Mons", "Hasselt", "Kortrijk", "Tournai", "Ostend",
        "Genk", "Sint-Niklaas", "Aalst", "Mechelen", "La Louviere",
        "Verviers", "Mouscron", "Arlon", "Bastogne", "Durbuy",
    ],
    "AT": [
        "Vienna", "Graz", "Linz", "Salzburg", "Innsbruck", "Klagenfurt",
        "Villach", "Wels", "Sankt Polten", "Dornbirn", "Wiener Neustadt",
        "Steyr", "Feldkirch", "Bregenz", "Leonding", "Hallein",
        "Bad Ischl", "Hallstatt", "Zell am See", "Kitzbuhel", "Sölden",
        "Mayrhofen", "St. Anton", "Ischgl", "Lech", "Oberstdorf",
    ],
    "CH": [
        "Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Winterthur",
        "Lucerne", "St. Gallen", "Lugano", "Biel", "Thun", "Biel/Bienne",
        "Köniz", "La Chaux-de-Fonds", "Fribourg", "Schaffhausen", "Chur",
        "Neuchatel", "Uster", "Sion", "Interlaken", "Montreux",
        "Davos", "St. Moritz", "Zermatt", "Grindelwald", "Lauterbrunnen",
    ],
    "GR": [
        "Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa", "Volos",
        "Rhodes", "Ioannina", "Chania", "Kavala", "Kalamata", "Corfu",
        "Serres", "Katerini", "Alexandroupoli", "Trikala", "Lamia",
        "Komotini", "Mytilene", "Chalkida", "Kozani", "Veria", "Drama",
    ],
    "CZ": [
        "Prague", "Brno", "Ostrava", "Plzen", "Liberec", "Olomouc",
        "Ceske Budejovice", "Hradec Kralove", "Usti nad Labem", "Pardubice",
        "Havířov", "Zlín", "Kladno", "Most", "Opava", "Karlovy Vary",
        "Teplice", "Jihlava", "Chomutov", "Děčín", "Krnov", "Prostějov",
        "Příbram", "Kolín", "Tábor", "Znojmo", "Písek", "Kroměříž",
    ],
    "HU": [
        "Budapest", "Debrecen", "Szeged", "Miskolc", "Pecs", "Gyor",
        "Nyiregyhaza", "Kecskemet", "Szekesfehervar", "Szombathely",
        "Szolnok", "Eger", "Tatabanya", "Kaposvar", "Veszprem",
        "Zalaegerszeg", "Sopron", "Erd", "Békéscsaba", "Hódmezővásárhely",
        "Nagykanizsa", "Dunaújváros", "Cegléd", "Baja", "Szigetszentmiklós",
    ],
    "SK": [
        "Bratislava", "Kosice", "Presov", "Zilina", "Nitra", "Banska Bystrica",
        "Trnava", "Trencin", "Martin", "Poprad", "Prievidza", "Zvolen",
        "Komárno", "Michalovce", "Spišská Nová Ves", "Levice", "Humenné",
        "Bardejov", "Lučenec", "Nové Zámky", "Pezinok", "Rimavská Sobota",
    ],
    "BG": [
        "Sofia", "Plovdiv", "Varna", "Burgas", "Ruse", "Stara Zagora",
        "Pleven", "Blagoevgrad", "Shumen", "Pazardzhik", "Veliko Tarnovo",
        "Haskovo", "Vidin", "Silistra", "Razgrad", "Targovishte",
        "Lovech", "Dobrich", "Kyustendil", "Smolyan", "Montana",
        "Kardzhali", "Troyan", "Teteven", "Chiprovtsi", "Berkovitsa",
    ],
    "HR": [
        "Zagreb", "Split", "Rijeka", "Osijek", "Zadar", "Pula",
        "Slavonski Brod", "Karlovac", "Varazdin", "Sibenik", "Dubrovnik",
        "Vukovar", "Vinkovci", "Virovitica", "Koprivnica", "Cakovec",
        "Pazin", "Gospic", "Knin", "Makarska", "Omis", "Trogir",
        "Nin", "Biograd", "Porec", "Novigrad", "Umag", "Opatija",
    ],
    "RS": [
        "Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica", "Zrenjanin",
        "Pancevo", "Cacak", "Kraljevo", "Novi Pazar", "Zadar", "Leskovac",
        "Uzice", "Valjevo", "Smederevo", "Vranje", "Sabac", "Sombor",
        "Pirot", "Kikinda", "Sremska Mitrovica", "Vrsac", "Bor", "Zajecar",
    ],
    "BA": [
        "Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar", "Bijeljina",
        "Brcko", "Bihać", "Bihac", "Trebinje", "Doboj", "Prijedor",
        "Livno", "Gorazde", "Visoko", "Gacko", "Foca", "Konjic",
        "Jablanica", "Mostar", "Capljina", "Nevesinje", "Bileca",
    ],
    "ME": [
        "Podgorica", "Niksic", "Herceg Novi", "Kotor", "Bar", "Budva",
        "Tivat", "Ulcinj", "Cetinje", "Pljevlja", "Bijelo Polje",
        "Berane", "Kotor", "Tivat", "Risan", "Perast", "Sveti Stefan",
    ],
    "MK": [
        "Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo", "Ohrid",
        "Veles", "Strumica", "Shtip", "Kavadarci", "Gostivar", "Struga",
        "Kicevo", "Prilep", "Kičevo", "Resen", "Demir Hisar",
    ],
    "AL": [
        "Tirana", "Durres", "Vlore", "Elbasan", "Shkoder", "Fier",
        "Korce", "Berat", "Lushnje", "Pogradec", "Gjirokaster",
        "Sarande", "Kukes", "Lezhe", "Peshkopi", "Burrel",
    ],
    "XK": [
        "Pristina", "Prizren", "Peja", "Mitrovica", "Gjilan", "Ferizaj",
        "Gjakova", "Podujevo", "Vushtrri", "Suva Reka", "Rahovec",
        "Kacanik", "Istog", "Klina", "Deçan", "Malisheve",
    ],
    "LT": [
        "Vilnius", "Kaunas", "Klaipeda", "Siauliai", "Panevezys", "Alytus",
        "Marijampole", "Mažeikiai", "Utena", "Telsiai", "Taurage",
        "Plunge", "Silale", "Raseiniai", "Kretinga", "Palanga",
    ],
    "LV": [
        "Riga", "Daugavpils", "Liepaja", "Jelgava", "Jurmala", "Ventspils",
        "Rezekne", "Valmiera", "Jekabpils", "Ogre", "Tukums", "Cesis",
        "Sigulda", "Jurmala", "Ventspils", "Liepaja", "Daugavpils",
    ],
    "EE": [
        "Tallinn", "Tartu", "Narva", "Parnu", "Kohtla-Järve", "Viljandi",
        "Rakvere", "Maardu", "Sillamäe", "Kuressaare", "Haapsalu",
        "Paide", "Valga", "Võru", "Jõgeva", "Järvamaa",
    ],
    "IS": [
        "Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri", "Keflavík",
        "Selfoss", "Vík", "Ísafjörður", "Seyðisfjörður", "Húsavík",
    ],
    "LU": [
        "Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange",
        "Ettelbruck", "Diekirch", "Wiltz", "Echternach", "Vianden",
        "Clervaux", "Mersch", "Capellen", "Bascharage", "Sanem",
    ],
    "CY": [
        "Nicosia", "Limassol", "Larnaca", "Paphos", "Strovolos",
        "Famagusta", "Kyrenia", "Paralimni", "Ayia Napa", "Protaras",
        "Troodos", "Platres", "Trooditissa", "Kakopetria", "Omodos",
    ],
    "MT": [
        "Valletta", "Birkirkara", "Mosta", "Qormi", "Sliema", "San Gwann",
        "Żabbar", "St. Paul's Bay", "Mdina", "Rabat", "Victoria",
        "Gozo", "Comino", "Marsascala", "Zebbug", "Paola",
    ],
    "SI": [
        "Ljubljana", "Maribor", "Celje", "Kranj", "Koper", "Velenje",
        "Novo Mesto", "Ptuj", "Trbovlje", "Kamnik", "Jesenice",
        "Nova Gorica", "Murska Sobota", "Bled", "Piran", "Postojna",
    ],
    "SK": [
        "Bratislava", "Košice", "Prešov", "Žilina", "Nitra", "Banská Bystrica",
        "Trnava", "Trenčín", "Martin", "Poprad", "Prievidza", "Zvolen",
        "Komárno", "Michalovce", "Spišská Nová Ves", "Levice", "Humenné",
    ],
    "BY": [
        "Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest",
        "Babruysk", "Baranovichi", "Borisov", "Pinsk", "Orsha",
        "Mozyr", "Lida", "Soligorsk", "Polotsk", "Novopolotsk",
    ],
    "GE": [
        "Tbilisi", "Batumi", "Kutaisi", "Rustavi", "Gori", "Zugdidi",
        "Poti", "Kobuleti", "Telavi", "Ozurgeti", "Mestia", "Kazbegi",
    ],
    "AM": [
        "Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan",
        "Abovyan", "Kapan", "Armavir", "Artashat", "Ijevan",
    ],
    "AZ": [
        "Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran", "Sheki",
        "Nakhchivan", "Shirvan", "Barda", "Goychay", "Zagatala",
    ],
    "KZ": [
        "Almaty", "Nur-Sultan", "Shymkent", "Aktobe", "Taraz", "Pavlodar",
        "Ust-Kamenogorsk", "Atyrau", "Karaganda", "Aktau", "Turkistan",
        "Kostanay", "Petropavlovsk", "Oral", "Temirtau", "Temir",
    ],
    "UZ": [
        "Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara",
        "Nukus", "Fergana", "Karakol", "Jizzakh", "Urgench", "Navoi",
    ],
    "TM": [
        "Ashgabat", "Turkmenabat", "Mary", "Balkanabat", "Dashoguz",
        "Bayramaly", "Turkmenbashi", "Tejen", "Mary", "Garabogaz",
    ],
    "KG": [
        "Bishkek", "Osh", "Jalal-Abad", "Karakol", "Tokmok", "Balykchy",
    ],
    "TJ": [
        "Dushanbe", "Khujand", "Kulob", "Qurghonteppa", "Istaravshan",
        "Tursunzoda", "Vahdat", "Konibodom", "Panjakent",
    ],
    "MN": [
        "Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan", "Mörön",
        "Bayankhongor", "Olgii", "Dalanzadgad", "Sainshand",
    ],
    "MM": [
        "Naypyidaw", "Yangon", "Mandalay", "Mawlamyine", "Bago",
        "Pathein", "Meiktila", "Sittwe", "Monywa", "Myingyan",
    ],
    "KH": [
        "Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville",
        "Kampong Cham", "Kampong Chhnang", "Pursat", "Koh Kong",
        "Kampot", "Kep", "Ta Khmau", "Prey Veng",
    ],
    "LA": [
        "Vientiane", "Luang Prabang", "Savannakhet", "Pakse",
        "Thakhek", "Vang Vieng", "Phonesavanh", "Xam Neua",
    ],
    "NP": [
        "Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar",
        "Birgunj", "Butwal", "Dharan", "Hetauda", "Janakpur",
        "Nepalgunj", "Dhangadhi", "Itahari", "Bhim Datta",
    ],
    "BD": [
        "Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Rangpur",
        "Barisal", "Comilla", "Gazipur", "Narayanganj", "Mymensingh",
        "Bogra", "Cox's Bazar", "Jessore", "Dinajpur", "Tangail",
    ],
    "LK": [
        "Colombo", "Sri Jayawardenepura Kotte", "Gampaha", "Kandy",
        "Galle", "Jaffna", "Negombo", "Ratnapura", "Trincomalee",
        "Batticaloa", "Matara", "Anuradhapura", "Polonnaruwa",
    ],
    "PK": [
        "Karachi", "Lahore", "Faisalabad", "Rawalpindi", "Multan",
        "Hyderabad", "Gujranwala", "Peshawar", "Quetta", "Islamabad",
        "Sialkot", "Bahawalpur", "Sargodha", "Sukkur", "Larkana",
    ],
    "AF": [
        "Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad",
        "Kunduz", "Lashkar Gah", "Taloqan", "Puli Khumri", "Sheberghan",
    ],
    "IQ": [
        "Baghdad", "Basra", "Erbil", "Mosul", "Sulaymaniyah", "Kirkuk",
        "Najaf", "Karbala", "Nasiriyah", "Amarah", "Dahuk", "Diwaniyah",
    ],
    "SA": [
        "Riyadh", "Jeddah", "Mecca", "Medina", "Dammam", "Tabuk",
        "Buraidah", "Khamis Mushait", "Abha", "Ha'il", "Jizan",
        "Najran", "Al Khobar", "Dhahran", "Al Jubail", "Yanbu",
        "Al Ula", "Al Baha", "Ta'if", "Bisha", "Qassim", "Sakaka",
        "Al Jawf", "Arar", "Rafha", "Turaif",
    ],
    "AE": [
        "Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah",
        "Fujairah", "Umm Al Quwain", "Al Ain", "Khor Fakkan",
        "Dibba Al-Fujairah", "Jebel Ali", "Dubai Marina", "JLT",
        "Business Bay", "Downtown Dubai", "Palm Jumeirah", "Jumeirah",
        "Al Barsha", "Motor City", "Sports City", "Dubai Sports City",
    ],
    "QA": [
        "Doha", "Al Wakrah", "Al Khor", "Dukhan", "Ras Laffan",
        "Al Rayyan", "Umm Salal", "Al Shahaniya", "Al Shamal",
    ],
    "BH": [
        "Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town",
        "Sitra", "Budaiya", "Juffair", "Seef", "Amwaj Islands",
    ],
    "OM": [
        "Muscat", "Salalah", "Sohar", "Nizwa", "Seeb", "Sur",
        "Ibri", "Rustaq", "Bahla", "Ibra", "Al Mudhaibi",
    ],
    "JO": [
        "Amman", "Irbid", "Zarqa", "Aqaba", "Mafraq", "Karak",
        "Madaba", "Salt", "Jerash", "Ma'an", "Ajloun", "Wadi Rum",
    ],
    "LB": [
        "Beirut", "Tripoli", "Sidon", "Tyre", "Zahle", "Byblos",
        "Broummana", "Chouf", "Baalbek", "Jounieh", "Batroun",
    ],
    "SY": [
        "Damascus", "Aleppo", "Homs", "Latakia", "Hama", "Deir ez-Zor",
        "Raqqa", "Idlib", "Daraa", "Qamishli", "Tartus",
    ],
    "YE": [
        "Sana'a", "Aden", "Taiz", "Al Hudaydah", "Ibb", "Dhamar",
        "Mukalla", "Amran", "Sayyan", "Zinjibar",
    ],
    "IR": [
        "Tehran", "Isfahan", "Mashhad", "Karaj", "Tabriz", "Shiraz",
        "Ahvaz", "Qom", "Kerman", "Urmia", "Yazd", "Bandar Abbas",
        "Rasht", "Kermanshah", "Zahedan", "Hamedan", "Khorramabad",
    ],
    "MAR": [
        "Casablanca", "Rabat", "Fez", "Marrakech", "Agadir", "Tangier",
        "Meknes", "Oujda", "Kenitra", "Tetouan", "Safi", "Mohammedia",
    ],
    "TN": [
        "Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte", "Gabès",
        "Monastir", "Nabeul", "Mahdia", "Tozeur", "Djerba",
    ],
    "DZ": [
        "Algiers", "Oran", "Constantine", "Annaba", "Blida", "Batna",
        "Setif", "Sidi Bel Abbes", "Skikda", "Biskra", "Tlemcen",
        "Bejaia", "Tizi Ouzou", "Djelfa", "M'sila", "Mostaganem",
    ],
    "LY": [
        "Tripoli", "Benghazi", "Misrata", "Tobruk", "Zliten", "Sabha",
        "Sirte", "Zawiya", "Al Khums", "Derna",
    ],
    "SD": [
        "Khartoum", "Omdurman", "Khartoum North", "Port Sudan",
        "El Obeid", "Kassala", "Nyala", "El Fasher", "Wad Madani",
    ],
    "ET": [
        "Addis Ababa", "Dire Dawa", "Mekelle", "Adama", "Gondar",
        "Hawassa", "Bahir Dar", "Jimma", "Dessie", "Harar",
    ],
    "TZ": [
        "Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Zanzibar City",
        "Mbeya", "Morogoro", "Tanga", "Tabora", "Kigoma",
    ],
    "UG": [
        "Kampala", "Gulu", "Lira", "Mbarara", "Jinja", "Mbale",
        "Masaka", "Fort Portal", "Arua", "Soroti",
    ],
    "RW": [
        "Kigali", "Butare", "Gitarama", "Ruhengeri", "Byumba",
        "Cyangugu", "Kibuye", "Gisenyi", "Kibungo",
    ],
    "BI": [
        "Bujumbura", "Gitega", "Muyinga", "Ruyigi", "Ngozi",
        "Bubanza", "Cibitoke", "Bujumbura Rural", "Makamba",
    ],
    "MZ": [
        "Maputo", "Beira", "Nampula", "Quelimane", "Tete",
        "Lichinga", "Pemba", "Inhambane", "Xai-Xai",
    ],
    "ZM": [
        "Lusaka", "Kitwe", "Ndola", "Kabwe", "Mufulira",
        "Livingstone", "Chingola", "Luanshya", "Kasama",
    ],
    "ZW": [
        "Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru",
        "Epworth", "Kwekwe", "Kadoma", "Masvingo", "Chinhoyi",
    ],
    "BW": [
        "Gaborone", "Francistown", "Molepolole", "Maun", "Serowe",
        "Selibe Phikwe", "Kanye", "Mahalapye", "Mogoditshane",
    ],
    "NA": [
        "Windhoek", "Rundu", "Walvis Bay", "Oshakati", "Swakopmund",
        "Katima Mulilo", "Grootfontein", "Otjiwarongo", "Gobabis",
    ],
    "SN": [
        "Dakar", "Touba", "Thiès", "Rufisque", "Kaolack",
        "Ziguinchor", "Saint-Louis", "Diourbel", "Louga",
    ],
    "ML": [
        "Bamako", "Sikasso", "Mopti", "Ségou", "Koutiala",
        "Gao", "Timbuktu", "Kayes", "Kidal",
    ],
    "BF": [
        "Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya",
        "Banfora", "Kaya", "Tenkodogo", "Houndé", "Fada N'Gourma",
    ],
    "NE": [
        "Niamey", "Zinder", "Maradi", "Agadez", "Tahoua",
        "Dosso", "Tillabéri", "Diffa",
    ],
    "TD": [
        "N'Djamena", "Moundou", "Abéché", "Sarh", "Kélo",
        "Koumra", "Am Timan", "Bongor",
    ],
    "CM": [
        "Douala", "Yaoundé", "Bamenda", "Bafoussam", "Garoua",
        "Maroua", "Ngaoundéré", "Ebolowa", "Buea", "Limbe",
    ],
    "CF": [
        "Bangui", "Bimbo", "Berbérati", "Carnot", "Bambari",
        "Bossangoa", "Bria", "Nola",
    ],
    "CD": [
        "Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga",
        "Bukavu", "Goma", "Mbandaka", "Matadi", "Tshikapa",
    ],
    "CG": [
        "Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando",
        "Impfondo", "Sibiti", "Madingou",
    ],
    "GA": [
        "Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda",
        "Lambaréné", "Tchibanga", "Koulamoutou",
    ],
    "GQ": [
        "Malabo", "Bata", "Ebebiyín", "Luba", "Evinayong",
    ],
    "ST": [
        "São Tomé", "Santo Amaro", "Neves", "Santana", "Trindade",
    ],
    "CV": [
        "Praia", "Mindelo", "Santa Maria", "Espargos", "Assomada",
    ],
    "MR": [
        "Nouakchott", "Nouadhibou", "Kaédi", "Rosso", "Atar",
        "Kiffa", "Zouérat", "Néma",
    ],
    "DJ": [
        "Djibouti City", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil",
    ],
    "SO": [
        "Mogadishu", "Hargeisa", "Berbera", "Kismayo", "Marka",
        "Baidoa", "Galkayo", "Bossaso",
    ],
    "ER": [
        "Asmara", "Keren", "Massawa", "Assab", "Mendefera",
    ],
    "SS": [
        "Juba", "Wau", "Malakal", "Bor", "Yei", "Rumbek",
    ],
    "LR": [
        "Monrovia", "Gbarnga", "Buchanan", "Harper", "Voinjama",
    ],
    "SL": [
        "Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Lunsar",
    ],
    "GN": [
        "Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé",
        "Mamou", "Faranah", "Boké",
    ],
    "GW": [
        "Bissau", "Bafatá", "Gabú", "Bissorã", "Cacheu",
    ],
    "TG": [
        "Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé",
    ],
    "BJ": [
        "Porto-Novo", "Cotonou", "Parakou", "Djougou", "Bohicon",
    ],
    "GA": [
        "Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda",
    ],
    "MU": [
        "Port Louis", "Beau Bassin", "Vacoas-Phoenix", "Curepipe",
        "Quatre Bornes", "Goodlands", "Mahébourg",
    ],
    "SC": [
        "Victoria", "Anse Boileau", "Beau Vallon", "Takamaka",
    ],
    "MG": [
        "Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa",
        "Mahajanga", "Toliara", "Antsiranana", "Antsakabe",
    ],
    "RE": [
        "Saint-Denis", "Saint-Pierre", "Saint-André", "Le Port",
        "La Possession", "Saint-Paul", "Saint-Benoît",
    ],
    "YT": [
        "Mamoudzou", "Koungou", "Dembeni", "Sada", "Dzaoudzi",
    ],
    "GF": [
        "Cayenne", "Matoury", "Saint-Laurent", "Kourou", "Remire-Montjoly",
    ],
    "MQ": [
        "Fort-de-France", "Le Lamentin", "Le Robert", "Sainte-Anne",
    ],
    "GP": [
        "Basse-Terre", "Les Abymes", "Saint-Martin", "Pointe-à-Pitre",
    ],
    "BL": [
        "Gustavia",
    ],
    "MF": [
        "Marigot",
    ],
    "PM": [
        "Saint-Pierre",
    ],
    "WF": [
        "Mata-Utu", "Sigave", "Alo",
    ],
    "PF": [
        "Papeete", "Faa'a", "Punaauia", "Moorea",
    ],
    "NC": [
        "Nouméa", "Dumbéa", "Mont-Dore", "Koné", "Thio",
    ],
    "VU": [
        "Port Vila", "Luganville", "Isangel", "Sola", "Lakatoro",
    ],
    "FJ": [
        "Suva", "Lautoka", "Nadi", "Labasa", "Ba", "Sigatoka",
    ],
    "WS": [
        "Apia", "Vaitele", "Faleula", "Siusega", "Malifa",
    ],
    "TO": [
        "Nuku'alofa", "Neiafu", "Pangai", "Ohonua",
    ],
    "PG": [
        "Port Moresby", "Lae", "Mount Hagen", "Madang", "Wewak",
        "Kokopo", "Goroka", "Daru",
    ],
    "SB": [
        "Honiara", "Auki", "Gizo", "Buala", "Tulagi",
    ],
    "TL": [
        "Dili", "Baucau", "Maliana", "Suai", "Lospalos",
    ],
    "BN": [
        "Bandar Seri Begawan", "Kuala Belait", "Tutong", "Seria",
    ],
    "MO": [
        "Macau",
    ],
    "HK": [
        "Hong Kong",
    ],
    "TW": [
        "Taipei", "Kaohsiung", "Taichung", "Tainan", "Taoyuan",
        "Hsinchu", "Keelung", "Chiayi", "Changhua", "Pingtung",
    ],
    "BD": [
        "Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet",
        "Rangpur", "Barisal", "Comilla", "Gazipur", "Narayanganj",
    ],
    "BT": [
        "Thimphu", "Phuntsholing", "Paro", "Gelephu", "Samdrup Jongkhar",
    ],
    "MV": [
        "Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi",
    ],
    "BN": [
        "Bandar Seri Begawan", "Kuala Belait", "Tutong", "Seria", "Temburong",
    ],
}
